### ISSUE TITLE
A one-way message delegation to Bürokratt and Bürokratt responds

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Open-Voice-Network-adoption#24]
~AS A Developer~
AS A Product Owner of a third-party chatbot
~I WANT TO have a test story to cover one-way message delegation to Bürokratt with Bürokratt responding~
I WANT TO send my OVON spec-based messages to Bürokratt and get its responses
~SO THAT I could use it as input when developing similar solutions~
SO THAT I could create an interoperable communication between my chatbot and Bürokratt

### Acceptance Criteria

- [ ] Use https://github.com/buerokratt/Open-Voice-Network-adoption/tree/dev as a source for dev
- [ ] Use https://github.com/open-voice-network/lib-interop/tree/main/javascript/sample-json/SuperMinSandBox20231018 as source for OVON messaging protocols

##### Chat initiation

- [x] #42
- [ ] Chat can be initiated by a mock localhost Bürokratt service, standard functionalities and requirements apply
- [ ] Chat can not be initiated by Bürokratt

##### Bürokratt responds

- [ ] Technical error in case of improper messaging format has been used by the chat initiator
- [ ] Standard Bürokratt responses based on actual natural language models will be used by default
- [ ] In case of providing a valid API key with the request, Bürokratt always responds as it normally would to any End Clients in production
- [ ] Bürokratt may switch to responding with random / mock answers in case of system overload

#### Graphical User Interface (GUI) functionalities

- [ ] A button to delegate the message to an actual Bürokratt instance

#### Example requests and responses

- [ ] What's the price of electricity for the current hour
- [ ] What's the cheapest hour for electricity tomorrow
- [ ] What's the current weather in Tallinn?
