### ISSUE TITLE
Accept any allowed protocols to have a conversation

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Open-Voice-Network-adoption#49]
AS A Product Owner
I WANT Bürokratt to have a conversation via any allowed protocols to
SO THAT it would be easier to onboard third-party chatbots and apply changes to their protocols

### Acceptance Criteria

- [ ] Only 1 endpoint `/chat` used for all types of interaction (start / reply to / end conversation)
- [ ] Based on message headers, message is forwarded to appropriate endpoint(s)
- [ ] Different protocols have different Ruuter DSLs
- [ ] Data Mapper is used to map `JSON` data according to the protocol

#### Scope

- [ ] #50
- [ ] Communication based on `Bürokratt` protocol

**Comment by turnerrainer** [comment]
Done, presented and accepted based on OVON requirements.
