### ISSUE TITLE
Delegate chats between different Participants

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Open-Voice-Network-adoption#8]
AS A Participant providing voice-based conversation
I WANT TO delegate the conversation from one Participant to another
SO THAT the End Client could get their response from appropriate Service Providers

#### Delegation of text-based chats

- [ ] #14
- [ ] #15
- [ ] #12
- [ ] #13

#### Delegation of voice-based chats

- [ ] #16
- [ ] #17
- [ ] #5 
- [ ] #6 

#### Specs

- [ ] #27
- [ ] #28

#### Documentation, Testing, and Demos

> The following is mandatory for all of the AC above

- [ ] A step-by-step technical guide to setting up a working solution locally
- [ ] Automated technical tests to cover all functionalities
- [ ] A filmed demo of a working solution published
